defaults:
  - process: process
  - model: model1
  - _self_

raw: 
  path: data/raw/Employee.csv

processed:
  dir: data/processed
  X_train: 
    name: X_train.csv
    path: ${processed.dir}/${processed.X_train.name}
  X_test:
    name: X_test.csv
    path: ${processed.dir}/${processed.X_test.name}
  y_train: 
    name: y_train.csv
    path: ${processed.dir}/${processed.y_train.name}
  y_test:
    name: y_test.csv
    path: ${processed.dir}/${processed.y_test.name}  

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

model:
  dir: models
  name: xgboost
  path: ${model.dir}/${model.name}


mlflow_tracking_ui: https://dagshub.com/abdulsamodazeez/project_employee.mlflow
mlflow_USERNAME: 9ca92a05cab055b161a8ee747439d73801098da9
